import bcrypt from 'bcryptjs';
import { db } from './jsonDb.js';

export const initialUsers = [
  {
    id: "usr_101",
    name: "Alex Morgan",
    email: "alex.morgan@eduplay.io",
    passwordHash: bcrypt.hashSync("password123", 10),
    role: "Full-Stack Apprentice",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250",
    level: 7,
    levelTitle: "Code Conjurer",
    currentXP: 3420,
    nextLevelXP: 4500,
    dailyStreak: 14,
    streakFreeze: 2,
    coursesCompleted: 6,
    quizAccuracy: 94,
    badgesEarned: 18,
    totalBadges: 25,
    totalHoursLearned: 58.5,
    league: "Diamond League",
    leagueRank: 4,
    joinedDate: "October 2025",
    bio: "Passionate about building full-stack web applications and machine learning experiments. Learning 30 mins every day!",
    preferences: {
      dailyGoalMinutes: 30,
      soundEffects: true,
      confettiEffects: true,
      reminderTime: "20:00",
      theme: "light",
    },
  },
  {
    id: "usr_102",
    name: "Sarah Chen",
    email: "sarah.chen@eduplay.io",
    passwordHash: bcrypt.hashSync("password123", 10),
    role: "AI Enthusiast",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200",
    level: 5,
    levelTitle: "Code Magician",
    currentXP: 2150,
    nextLevelXP: 3000,
    dailyStreak: 8,
    streakFreeze: 1,
    coursesCompleted: 3,
    quizAccuracy: 89,
    badgesEarned: 11,
    totalBadges: 25,
    totalHoursLearned: 34.0,
    league: "Gold League",
    leagueRank: 2,
    joinedDate: "January 2026",
    bio: "Exploring deep learning, computer vision, and Python.",
    preferences: {
      dailyGoalMinutes: 45,
      soundEffects: true,
      confettiEffects: true,
      reminderTime: "19:00",
      theme: "light",
    },
  }
];

export const initialCourses = [
  {
    id: "py-101",
    title: "Python Programming: Zero to Hero",
    slug: "python-programming",
    category: "Python",
    difficulty: "Beginner",
    rating: 4.9,
    ratingCount: 1420,
    enrolledCount: 14280,
    totalLessons: 32,
    completedLessons: 21,
    xpReward: 850,
    estimatedHours: 18,
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "🐍",
    instructor: {
      name: "Dr. Elena Rostova",
      title: "Senior Python Architect & CS Professor",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200",
    },
    description: "Master Python fundamentals from data types to object-oriented programming with interactive coding challenges and automated unit tests.",
    currentLesson: {
      id: "py-l-22",
      title: "Loops and Iterations",
      module: "Module 4: Control Flow & Iterations",
      duration: "12 min",
      type: "interactive",
    },
    modules: [
      {
        id: "mod-1",
        title: "Module 1: Foundations & Variables",
        lessons: [
          { id: "py-l-1", title: "Introduction to Python & Syntax", duration: "8 min", type: "theory", completed: true, xp: 25 },
          { id: "py-l-2", title: "Variables, Numbers & String Formatting", duration: "12 min", type: "interactive", completed: true, xp: 35 },
          { id: "py-l-3", title: "Quiz: Data Types & Casting", duration: "10 min", type: "quiz", completed: true, xp: 50 },
        ],
      },
      {
        id: "mod-2",
        title: "Module 2: Lists, Dictionaries & Tuples",
        lessons: [
          { id: "py-l-4", title: "Lists & Array Operations", duration: "15 min", type: "interactive", completed: true, xp: 40 },
          { id: "py-l-5", title: "Dictionary Key-Value Maps", duration: "14 min", type: "interactive", completed: true, xp: 40 },
          { id: "py-l-6", title: "Interactive Challenge: Shopping Cart Manager", duration: "20 min", type: "simulation", completed: true, xp: 60 },
        ],
      },
      {
        id: "mod-3",
        title: "Module 3: Functions & Modular Code",
        lessons: [
          { id: "py-l-7", title: "Defining Functions & Default Arguments", duration: "15 min", type: "interactive", completed: true, xp: 45 },
          { id: "py-l-8", title: "Scope, Closures & Lambda Expressions", duration: "18 min", type: "interactive", completed: true, xp: 50 },
          { id: "py-l-9", title: "Quiz: Function Mastery", duration: "12 min", type: "quiz", completed: true, xp: 50 },
        ],
      },
      {
        id: "mod-4",
        title: "Module 4: Control Flow & Iterations",
        lessons: [
          { id: "py-l-21", title: "Conditionals & Logical Operators", duration: "10 min", type: "theory", completed: true, xp: 30 },
          { id: "py-l-22", title: "Loops and Iterations", duration: "15 min", type: "interactive", completed: false, isCurrent: true, xp: 60 },
          { id: "py-l-23", title: "List Comprehensions & Generators", duration: "18 min", type: "interactive", completed: false, xp: 55 },
          { id: "py-l-24", title: "Simulation Lab: Prime Number Sieve", duration: "25 min", type: "simulation", completed: false, xp: 80 },
        ],
      },
      {
        id: "mod-5",
        title: "Module 5: Object-Oriented Python",
        lessons: [
          { id: "py-l-25", title: "Classes, Objects & Attributes", duration: "20 min", type: "interactive", completed: false, xp: 60 },
          { id: "py-l-26", title: "Inheritance & Polymorphism", duration: "22 min", type: "interactive", completed: false, xp: 70 },
          { id: "py-l-27", title: "Final Capstone Project: Text RPG Game", duration: "45 min", type: "simulation", completed: false, xp: 150 },
        ],
      },
    ],
  },
  {
    id: "web-201",
    title: "Interactive Web Mastery: Modern JS & React",
    slug: "web-development-react",
    category: "Web Development",
    difficulty: "Beginner",
    rating: 4.85,
    ratingCount: 2310,
    enrolledCount: 21500,
    totalLessons: 45,
    completedLessons: 36,
    xpReward: 1200,
    estimatedHours: 28,
    image: "https://images.unsplash.com/photo-1593720213428-28a5b9e94613?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "⚛️",
    instructor: {
      name: "Marcus Vance",
      title: "Principal Frontend Engineer",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200",
    },
    description: "Learn how the modern web works. Build dynamic user interfaces with JavaScript ES6+, React components, state hooks, and API integrations.",
    currentLesson: {
      id: "web-l-37",
      title: "Async/Await & Fetch API",
      module: "Module 6: Asynchronous JavaScript",
      duration: "14 min",
      type: "interactive",
    },
    modules: [],
  },
  {
    id: "algo-301",
    title: "Data Structures & Algorithmic Quests",
    slug: "data-structures-algorithms",
    category: "Algorithms",
    difficulty: "Intermediate",
    rating: 4.95,
    ratingCount: 980,
    enrolledCount: 9800,
    totalLessons: 40,
    completedLessons: 12,
    xpReward: 1500,
    estimatedHours: 32,
    image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "⚡",
    instructor: {
      name: "Sophia Sterling",
      title: "Algorithm Specialist & Competitive Programmer",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200",
    },
    description: "Conquer Big-O notation, linked lists, binary search trees, dynamic programming, and graph traversals through gamified visualizations.",
    currentLesson: {
      id: "algo-l-13",
      title: "Binary Search Tree Traversals (Inorder/Preorder)",
      module: "Module 3: Trees & Graphs",
      duration: "20 min",
      type: "interactive",
    },
    modules: [],
  },
  {
    id: "ai-401",
    title: "Machine Learning & Neural Network Sims",
    slug: "machine-learning-ai",
    category: "AI & Data",
    difficulty: "Advanced",
    rating: 4.9,
    ratingCount: 1120,
    enrolledCount: 12100,
    totalLessons: 28,
    completedLessons: 0,
    xpReward: 1800,
    estimatedHours: 26,
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "🧠",
    instructor: {
      name: "Kenji Sato",
      title: "AI Research Scientist",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200",
    },
    description: "Tear open black-box algorithms! Visually tune weights, experiment with loss landscapes, and train computer vision models right in your browser.",
    currentLesson: {
      id: "ai-l-1",
      title: "Perceptron Fundamentals & Gradient Descent",
      module: "Module 1: Foundations of Deep Learning",
      duration: "18 min",
      type: "interactive",
    },
    modules: [],
  },
  {
    id: "sec-202",
    title: "Cybersecurity Defense Arena: Ethical Hacking",
    slug: "cybersecurity-defense",
    category: "Security",
    difficulty: "Intermediate",
    rating: 4.78,
    ratingCount: 840,
    enrolledCount: 8300,
    totalLessons: 24,
    completedLessons: 4,
    xpReward: 950,
    estimatedHours: 20,
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "🛡️",
    instructor: {
      name: "Tariq Al-Mansoor",
      title: "Lead Penetration Tester & SecOps",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200",
    },
    description: "Learn web application security vulnerabilities: SQL injection, XSS, CSRF, and authentication bypasses in safely isolated sandbox labs.",
    currentLesson: {
      id: "sec-l-5",
      title: "Defending Against Cross-Site Scripting (XSS)",
      module: "Module 2: Web Injection Attacks",
      duration: "16 min",
      type: "simulation",
    },
    modules: [],
  },
  {
    id: "game-102",
    title: "Game Dev Essentials with 2D Physics & Canvas",
    slug: "game-development-2d",
    category: "Game Dev",
    difficulty: "Beginner",
    rating: 4.88,
    ratingCount: 1650,
    enrolledCount: 16400,
    totalLessons: 36,
    completedLessons: 0,
    xpReward: 1400,
    estimatedHours: 24,
    image: "https://images.unsplash.com/photo-1556438064-2d7646166914?auto=format&fit=crop&q=80&w=600",
    badgeIcon: "🎮",
    instructor: {
      name: "Claire Becker",
      title: "Indie Game Developer & Physics Engineer",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200",
    },
    description: "Create responsive 2D games from scratch! Build collision detectors, particle systems, gravity simulators, and sound synthesizers.",
    currentLesson: {
      id: "game-l-1",
      title: "Setting Up HTML Canvas & Game Loop",
      module: "Module 1: The Core Loop",
      duration: "15 min",
      type: "interactive",
    },
    modules: [],
  },
];

export const initialBadges = [
  {
    id: "b-1",
    name: "First Code Strike",
    category: "Learning",
    icon: "🚀",
    color: "from-blue-500 to-indigo-600",
    description: "Completed your first interactive lesson on EduPlay.",
    unlocked: true,
    unlockedAt: "3 weeks ago",
    rarity: "Common",
    xp: 50,
  },
  {
    id: "b-2",
    name: "7-Day Streak Warrior",
    category: "Streaks",
    icon: "🔥",
    color: "from-amber-500 to-orange-600",
    description: "Maintained a continuous daily learning streak for 7 days.",
    unlocked: true,
    unlockedAt: "1 week ago",
    rarity: "Rare",
    xp: 150,
  },
  {
    id: "b-3",
    name: "Bug Hunter",
    category: "Mastery",
    icon: "🐛",
    color: "from-emerald-500 to-teal-600",
    description: "Successfully identified and debugged 10 code logic errors.",
    unlocked: true,
    unlockedAt: "4 days ago",
    rarity: "Rare",
    xp: 200,
  },
  {
    id: "b-4",
    name: "Quiz Grandmaster",
    category: "Mastery",
    icon: "🎯",
    color: "from-purple-500 to-pink-600",
    description: "Scored 100% on 5 consecutive lesson quizzes.",
    unlocked: true,
    unlockedAt: "Yesterday",
    rarity: "Epic",
    xp: 300,
  },
  {
    id: "b-5",
    name: "Night Owl Coder",
    category: "Special",
    icon: "🦉",
    color: "from-indigo-600 to-slate-800",
    description: "Completed a challenging lesson between 10:00 PM and 2:00 AM.",
    unlocked: true,
    unlockedAt: "2 weeks ago",
    rarity: "Common",
    xp: 50,
  },
  {
    id: "b-6",
    name: "Speed Demon",
    category: "Mastery",
    icon: "⚡",
    color: "from-yellow-400 to-amber-600",
    description: "Finished a 10-question quiz in under 90 seconds with >90% accuracy.",
    unlocked: true,
    unlockedAt: "5 days ago",
    rarity: "Rare",
    xp: 150,
  },
  {
    id: "b-7",
    name: "Century Solved",
    category: "Learning",
    icon: "💯",
    color: "from-rose-500 to-red-600",
    description: "Solved over 100 interactive quiz questions and code prompts.",
    unlocked: true,
    unlockedAt: "2 days ago",
    rarity: "Epic",
    xp: 250,
  },
  {
    id: "b-8",
    name: "30-Day Legend",
    category: "Streaks",
    icon: "👑",
    color: "from-amber-400 to-yellow-600",
    description: "Maintain an unbroken daily learning streak for 30 consecutive days.",
    unlocked: false,
    progress: 14,
    maxProgress: 30,
    rarity: "Legendary",
    xp: 500,
  },
  {
    id: "b-9",
    name: "Polyglot Architect",
    category: "Learning",
    icon: "🌐",
    color: "from-cyan-500 to-blue-600",
    description: "Complete at least one full module in 3 different programming languages.",
    unlocked: false,
    progress: 2,
    maxProgress: 3,
    rarity: "Epic",
    xp: 350,
  },
  {
    id: "b-10",
    name: "Level 10 Titan",
    category: "Special",
    icon: "⚔️",
    color: "from-violet-600 to-purple-900",
    description: "Ascend to Level 10 on the EduPlay platform.",
    unlocked: false,
    progress: 7,
    maxProgress: 10,
    rarity: "Legendary",
    xp: 600,
  },
];

export const initialDailyChallenge = {
  id: "daily-20260929",
  title: "Debug the Infinite Loop!",
  category: "Python & Logic",
  difficulty: "Medium",
  xpReward: 100,
  streakBonus: "+1 Day",
  estimatedMinutes: 5,
  timeLeft: "08h 34m",
  completed: false,
  description: "Find and fix the logic flaw causing the `while` loop to run indefinitely when searching for target elements.",
  problemSnippet: `def find_target(arr, target):
    i = 0
    while i < len(arr):
        if arr[i] == target:
            return i
        # BUG: Missing iterator update!
    return -1`,
  options: [
    { id: "opt-1", text: "Add 'i += 1' inside the while block before or after the check", correct: true },
    { id: "opt-2", text: "Change 'while i < len(arr)' to 'while i <= len(arr)'", correct: false },
    { id: "opt-3", text: "Replace 'return i' with 'break'", correct: false },
    { id: "opt-4", text: "Remove the 'return -1' statement", correct: false },
  ],
  explanation: "Without incrementing the loop index variable `i` (using `i += 1`), `i` remains 0 forever, creating an infinite loop whenever `arr[0]` is not the target.",
};

export const initialLeaderboard = [
  { rank: 1, name: "Liam Chen", avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200", xp: 5420, streak: 32, league: "Diamond", badge: "🥇 Grandmaster", userId: "usr_lead_1" },
  { rank: 2, name: "Zara Patel", avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200", xp: 4890, streak: 28, league: "Diamond", badge: "🥈 Code Wizard", userId: "usr_lead_2" },
  { rank: 3, name: "Mateo Rossi", avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200", xp: 4310, streak: 21, league: "Diamond", badge: "🥉 Speedster", userId: "usr_lead_3" },
  { rank: 4, name: "Alex Morgan", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250", xp: 3420, streak: 14, league: "Diamond", badge: "⚡ Top 5", userId: "usr_101" },
  { rank: 5, name: "Hana Takahashi", avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=200", xp: 3290, streak: 19, league: "Diamond", badge: "🎯 Ace", userId: "usr_lead_5" },
  { rank: 6, name: "David Kim", avatar: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&q=80&w=200", xp: 2980, streak: 11, league: "Diamond", badge: "🔥 Streaker", userId: "usr_lead_6" },
  { rank: 7, name: "Aisha Diallo", avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=200", xp: 2850, streak: 9, league: "Diamond", badge: "💡 Scholar", userId: "usr_lead_7" },
  { rank: 8, name: "Lucas Müller", avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=200", xp: 2640, streak: 15, league: "Diamond", badge: "🚀 Explorer", userId: "usr_lead_8" },
];

export const initialLearningPaths = [
  {
    id: "path-fs",
    title: "Full-Stack Web Architect",
    description: "From semantic HTML & modern CSS to React, Node.js, databases and cloud deployment.",
    totalXP: 5500,
    estimatedWeeks: 12,
    category: "Web & Software",
    color: "from-blue-600 to-indigo-600",
    nodes: [
      { id: "n-1", title: "HTML5 & CSS Modern Grid/Flexbox", status: "completed", xp: 600, icon: "🎨" },
      { id: "n-2", title: "JavaScript ES6+ & DOM Events", status: "completed", xp: 900, icon: "⚡" },
      { id: "n-3", title: "React Component Lifecycle & Hooks", status: "current", xp: 1200, icon: "⚛️" },
      { id: "n-4", title: "State Management & Next.js Basics", status: "locked", xp: 1100, icon: "🔄" },
      { id: "n-5", title: "REST APIs, Node & Express Backends", status: "locked", xp: 1000, icon: "🚀" },
      { id: "n-6", title: "PostgreSQL & Database Design", status: "locked", xp: 700, icon: "💾" },
    ],
  },
  {
    id: "path-py",
    title: "Python Data & Automation Specialist",
    description: "Automate boring tasks, analyze complex data sets, and build backend microservices with Python.",
    totalXP: 4800,
    estimatedWeeks: 10,
    category: "Python & Data",
    color: "from-emerald-600 to-teal-600",
    nodes: [
      { id: "py-n-1", title: "Python Syntax & Data Structures", status: "completed", xp: 800, icon: "🐍" },
      { id: "py-n-2", title: "Loops, Iterations & Functions", status: "current", xp: 850, icon: "🔁" },
      { id: "py-n-3", title: "Pandas & Data Wrangling", status: "locked", xp: 1100, icon: "📊" },
      { id: "py-n-4", title: "Data Visualization & Dashboards", status: "locked", xp: 950, icon: "📈" },
      { id: "py-n-5", title: "FastAPI Backend & Scrapers", status: "locked", xp: 1100, icon: "⚡" },
    ],
  },
  {
    id: "path-ai",
    title: "AI & Neural Networks Engineer",
    description: "Deep dive into machine learning models, transformers, prompt engineering, and model fine-tuning.",
    totalXP: 6200,
    estimatedWeeks: 14,
    category: "AI & ML",
    color: "from-purple-600 to-pink-600",
    nodes: [
      { id: "ai-n-1", title: "Linear Algebra & Probability for AI", status: "completed", xp: 900, icon: "📐" },
      { id: "ai-n-2", title: "Scikit-Learn Classification & Regression", status: "locked", xp: 1200, icon: "🤖" },
      { id: "ai-n-3", title: "Neural Networks & Backpropagation", status: "locked", xp: 1400, icon: "🧠" },
      { id: "ai-n-4", title: "Computer Vision & CNNs", status: "locked", xp: 1300, icon: "👁️" },
      { id: "ai-n-5", title: "Transformers & LLM Integrations", status: "locked", xp: 1400, icon: "✨" },
    ],
  },
];

export const initialNotifications = [
  { id: "notif-1", userId: "usr_101", title: "Streak Preserved! 🔥", message: "You logged in today! Your streak is now 14 days strong.", time: "10 mins ago", unread: true },
  { id: "notif-2", userId: "usr_101", title: "Daily Challenge Ready 🎯", message: "'Debug the Infinite Loop!' is waiting for you with +100 XP.", time: "1 hour ago", unread: true },
  { id: "notif-3", userId: "usr_101", title: "Leaderboard Update 🏆", message: "You climbed to Rank #4 in the Diamond League! Only 890 XP to Top 3.", time: "Yesterday", unread: false },
  { id: "notif-4", userId: "usr_101", title: "New Badge Unlocked 🎯", message: "You earned 'Quiz Grandmaster' for scoring 100% on 5 quizzes.", time: "2 days ago", unread: false },
];

export const initialTargetBlasterQuestions = [
  { id: 1, question: "Which data structure follows LIFO?", options: ["Stack", "Queue", "Array", "Tree"], correctAnswer: "Stack", explanation: "A Stack follows Last In, First Out (LIFO). Elements added last are removed first.", hint: "Think about a vertical stack of cafeteria plates — you remove the top plate first.", difficulty: "easy", topic: "Stacks" },
  { id: 2, question: "Which data structure follows FIFO?", options: ["Queue", "Stack", "Binary Tree", "Hash Map"], correctAnswer: "Queue", explanation: "A Queue operates on First In, First Out (FIFO) principles. The first item enqueued is dequeued first.", hint: "Think about a real-world checkout line or queue of people waiting for tickets.", difficulty: "easy", topic: "Queues" },
  { id: 3, question: "What is the average time complexity of searching in a Hash Table?", options: ["O(1)", "O(n)", "O(log n)", "O(n²)"], correctAnswer: "O(1)", explanation: "Hash tables provide average O(1) constant time lookups by hashing keys directly to memory buckets.", hint: "Direct key-to-bucket hashing allows near-instantaneous indexing without iterating.", difficulty: "easy", topic: "Hash Tables" },
  { id: 4, question: "Which data structure uses pointers to connect sequential nodes in memory?", options: ["Linked List", "Fixed Array", "Bitmask", "Tuple"], correctAnswer: "Linked List", explanation: "Linked lists consist of nodes where each node stores a data value and a pointer/reference to the next node.", hint: "Unlike contiguous arrays, these items are scattered in memory linked by references.", difficulty: "easy", topic: "Linked Lists" },
  { id: 5, question: "What is the worst-case time complexity of standard QuickSort?", options: ["O(n²)", "O(n log n)", "O(n)", "O(log n)"], correctAnswer: "O(n²)", explanation: "When partitions are extremely unbalanced (e.g. already sorted array with poor pivot selection), QuickSort degrades to O(n²).", hint: "Consider what happens when the pivot chosen is always the smallest or largest element.", difficulty: "medium", topic: "Algorithms" },
  { id: 6, question: "Which tree traversal visits Root, then Left, then Right subtree?", options: ["Pre-order", "In-order", "Post-order", "Level-order"], correctAnswer: "Pre-order", explanation: "Pre-order traversal processes the current node first (Root), followed recursively by Left and Right child subtrees.", hint: "The prefix 'Pre' indicates the root/current node is processed before any subtrees.", difficulty: "medium", topic: "Binary Trees" },
  { id: 7, question: "Which algorithm is optimal for finding the shortest path in an unweighted graph?", options: ["Breadth-First Search (BFS)", "Depth-First Search (DFS)", "Bellman-Ford", "Kruskal's Algorithm"], correctAnswer: "Breadth-First Search (BFS)", explanation: "BFS explores vertices level by level, ensuring the first time a node is reached corresponds to the minimum edge distance in unweighted graphs.", hint: "Think about exploring in concentric ripple waves level-by-level from the start node.", difficulty: "medium", topic: "Graphs" },
  { id: 8, question: "What data structure is typically used to implement Breadth-First Search?", options: ["Queue", "Stack", "Min-Heap", "Trie"], correctAnswer: "Queue", explanation: "BFS relies on a FIFO queue to explore nodes in the order they were discovered layer by layer.", hint: "Nodes discovered first must be visited and expanded first (FIFO).", difficulty: "easy", topic: "Queues" },
  { id: 9, question: "In Python, which built-in function returns both the index and value during loop iteration?", options: ["enumerate()", "zip()", "range()", "map()"], correctAnswer: "enumerate()", explanation: "`enumerate(iterable)` yields 2-tuples containing `(index, item)` on each iteration cycle.", hint: "It numbers or counts each item in the collection automatically as you iterate.", difficulty: "easy", topic: "Python" },
  { id: 10, question: "Which data structure is best suited for implementing an LRU (Least Recently Used) Cache?", options: ["Hash Map + Doubly Linked List", "Binary Search Tree", "Single Array", "Max Heap"], correctAnswer: "Hash Map + Doubly Linked List", explanation: "A Hash Map provides O(1) key lookups, while a Doubly Linked List provides O(1) removal and insertion at head/tail.", hint: "You need both instant O(1) key lookups and instant O(1) node reordering.", difficulty: "hard", topic: "System Design" }
];

export const initialAnalytics = {
  weeklyActivity: [
    { day: "Mon", hours: 1.2, xp: 240, lessons: 3 },
    { day: "Tue", hours: 0.8, xp: 180, lessons: 2 },
    { day: "Wed", hours: 1.5, xp: 320, lessons: 4 },
    { day: "Thu", hours: 2.1, xp: 450, lessons: 5 },
    { day: "Fri", hours: 1.0, xp: 210, lessons: 2 },
    { day: "Sat", hours: 2.8, xp: 580, lessons: 6 },
    { day: "Sun (Today)", hours: 1.4, xp: 310, lessons: 3 },
  ],
  skillBreakdown: [
    { subject: "Python & Logic", score: 88, fullMark: 100 },
    { subject: "Web & React", score: 92, fullMark: 100 },
    { subject: "Algorithms", score: 76, fullMark: 100 },
    { subject: "Data & AI", score: 64, fullMark: 100 },
    { subject: "Security", score: 70, fullMark: 100 },
    { subject: "System Design", score: 58, fullMark: 100 },
  ],
  accuracyHistory: [
    { week: "Wk 1", accuracy: 82, quizzes: 8 },
    { week: "Wk 2", accuracy: 86, quizzes: 12 },
    { week: "Wk 3", accuracy: 89, quizzes: 14 },
    { week: "Wk 4", accuracy: 91, quizzes: 15 },
    { week: "Wk 5", accuracy: 93, quizzes: 18 },
    { week: "Wk 6 (Current)", accuracy: 96, quizzes: 16 },
  ],
};

export async function seedAll() {
  await db.seedIfEmpty('users', initialUsers);
  await db.seedIfEmpty('courses', initialCourses);
  await db.seedIfEmpty('badges', initialBadges);
  await db.seedIfEmpty('dailyChallenges', [initialDailyChallenge]);
  await db.seedIfEmpty('quizResults', []);
  await db.seedIfEmpty('leaderboard', initialLeaderboard);
  await db.seedIfEmpty('learningPaths', initialLearningPaths);
  await db.seedIfEmpty('notifications', initialNotifications);
  await db.seedIfEmpty('targetBlasterQuestions', initialTargetBlasterQuestions);
  await db.seedIfEmpty('analytics', [initialAnalytics]);
}
